services:
    simple_reports:
        class: BisonLab\ReportsBundle\Service\Reports
        arguments: 
            container: '@service_container'
            #report_classes: bisonlab_reports.report_classes
            #default_filestore: bisonlab_reports.default_filestore

            report_classes: %bisonlab_reports.report_classes%
            default_filestore: bisonlab_reports.default_filestore
