services:
    _defaults:
        autowire: true
        autoconfigure: true

    BisonLab\ReportsBundle\:
        resource: '../'
        exclude:
            - '../DependencyInjection/'
            - '../Lib/'

    BisonLab\ReportsBundle\Service\Reports:
        arguments: [!tagged_locator { tag: 'bisonlab.reports', index_by: 'key' }]
        autowire: true
        autoconfigure: true
